#!/usr/bin/env bash
# Home Assistant entrypoint for OpenOMS.
#
# Responsibilities:
#   1. Read user-supplied options from /data/options.json (HA Supervisor).
#   2. Generate strong random secrets for anything left blank and persist them
#      to /data/secrets.env so they survive restarts / rebuilds.
#   3. Export the merged config to /run/openoms/env, which is then sourced by
#      every s6 service script.
#   4. Prepare the persistent directories used by PostgreSQL / Redis / uploads.
#   5. exec into s6-overlay /init (or whatever CMD was passed).
set -euo pipefail

OPTIONS_FILE="${OPTIONS_FILE:-/data/options.json}"
SECRETS_FILE="/data/secrets.env"
ENV_FILE="/run/openoms/env"

mkdir -p /data /data/postgres /data/redis /data/uploads /run/openoms /run/postgresql

# Make sure the postgres user can write to its directories. UID/GID come from
# the apk-installed postgresql17 package.
chown -R postgres:postgres /data/postgres /data/redis /run/postgresql 2>/dev/null || true
chmod 700 /data/postgres

opt() {
    local key="$1" default="${2:-}"
    if [[ -f "${OPTIONS_FILE}" ]]; then
        jq -r --arg d "${default}" --arg k "${key}" \
            '(.[$k] | tostring) as $v | if ($v == "null" or $v == "") then $d else $v end' \
            "${OPTIONS_FILE}"
    else
        printf '%s' "${default}"
    fi
}

rand_b64() { openssl rand -base64 "$1" | tr -d '\n' | tr -d '='; }
rand_hex() { openssl rand -hex "$1" | tr -d '\n'; }

# Load previously generated secrets (if any) so we keep stable values across restarts.
if [[ -f "${SECRETS_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${SECRETS_FILE}"
fi

# User-provided values override what's on disk.
POSTGRES_PASSWORD="$(opt postgres_password "${POSTGRES_PASSWORD:-}")"
POSTGRES_APP_PASSWORD="$(opt postgres_app_password "${POSTGRES_APP_PASSWORD:-}")"
JWT_SECRET="$(opt jwt_secret "${JWT_SECRET:-}")"
ENCRYPTION_KEY="$(opt encryption_key "${ENCRYPTION_KEY:-}")"

# Auto-generate anything still missing.
[[ -z "${POSTGRES_PASSWORD:-}"     ]] && POSTGRES_PASSWORD="$(rand_b64 24)"
[[ -z "${POSTGRES_APP_PASSWORD:-}" ]] && POSTGRES_APP_PASSWORD="$(rand_b64 24)"
[[ -z "${JWT_SECRET:-}"            ]] && JWT_SECRET="$(rand_b64 64)"
[[ -z "${ENCRYPTION_KEY:-}"        ]] && ENCRYPTION_KEY="$(rand_hex 32)"

umask 077
cat > "${SECRETS_FILE}" <<EOF
# Auto-generated on first boot, then preserved across restarts.
# To rotate, edit the add-on Configuration tab (or this file) and restart.
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
EOF
umask 022

# Non-secret app config.
BASE_URL="$(opt base_url "http://homeassistant.local:8080")"
FRONTEND_URL="$(opt frontend_url "http://homeassistant.local:3000")"
TRUSTED_PROXY_CIDRS="$(opt trusted_proxy_cidrs "")"
ALLEGRO_CLIENT_ID="$(opt allegro_client_id "")"
ALLEGRO_CLIENT_SECRET="$(opt allegro_client_secret "")"
ALLEGRO_WEBHOOK_SECRET="$(opt allegro_webhook_secret "")"
INPOST_API_TOKEN="$(opt inpost_api_token "")"
INPOST_ORGANIZATION_ID="$(opt inpost_organization_id "")"
INPOST_WEBHOOK_SECRET="$(opt inpost_webhook_secret "")"
INPOST_GEOWIDGET_TOKEN="$(opt inpost_geowidget_token "")"
OPENAI_API_KEY="$(opt openai_api_key "")"
OPENAI_MODEL="$(opt openai_model "gpt-4o-mini")"
FEATURE_ALLEGRO="$(opt feature_allegro "true")"
FEATURE_INPOST="$(opt feature_inpost "true")"
WORKERS_ENABLED="$(opt workers_enabled "true")"
LOG_LEVEL="$(opt log_level "info")"

# DSNs for the bundled Postgres. Both connect over the local loopback.
DATABASE_URL="postgres://openoms_app:${POSTGRES_APP_PASSWORD}@127.0.0.1:5432/openoms?sslmode=disable"
WORKER_DATABASE_URL="postgres://openoms:${POSTGRES_PASSWORD}@127.0.0.1:5432/openoms?sslmode=disable"
REDIS_URL="redis://127.0.0.1:6379"

# Materialise an env file that every s6 service script can `source`.
cat > "${ENV_FILE}" <<EOF
# Generated by /entrypoint.sh — do not edit (regenerated on every start).
export POSTGRES_PASSWORD='${POSTGRES_PASSWORD}'
export POSTGRES_APP_PASSWORD='${POSTGRES_APP_PASSWORD}'
export JWT_SECRET='${JWT_SECRET}'
export ENCRYPTION_KEY='${ENCRYPTION_KEY}'
export DATABASE_URL='${DATABASE_URL}'
export WORKER_DATABASE_URL='${WORKER_DATABASE_URL}'
export REDIS_URL='${REDIS_URL}'
export BASE_URL='${BASE_URL}'
export FRONTEND_URL='${FRONTEND_URL}'
export TRUSTED_PROXY_CIDRS='${TRUSTED_PROXY_CIDRS}'
export ALLEGRO_CLIENT_ID='${ALLEGRO_CLIENT_ID}'
export ALLEGRO_CLIENT_SECRET='${ALLEGRO_CLIENT_SECRET}'
export ALLEGRO_WEBHOOK_SECRET='${ALLEGRO_WEBHOOK_SECRET}'
export INPOST_API_TOKEN='${INPOST_API_TOKEN}'
export INPOST_ORGANIZATION_ID='${INPOST_ORGANIZATION_ID}'
export INPOST_WEBHOOK_SECRET='${INPOST_WEBHOOK_SECRET}'
export INPOST_GEOWIDGET_TOKEN='${INPOST_GEOWIDGET_TOKEN}'
export OPENAI_API_KEY='${OPENAI_API_KEY}'
export OPENAI_MODEL='${OPENAI_MODEL}'
export FEATURE_ALLEGRO='${FEATURE_ALLEGRO}'
export FEATURE_INPOST='${FEATURE_INPOST}'
export WORKERS_ENABLED='${WORKERS_ENABLED}'
export LOG_LEVEL='${LOG_LEVEL}'
export PORT='8080'
export ENV='production'
export NODE_ENV='production'
export HOSTNAME='0.0.0.0'
export UPLOAD_DIR='/data/uploads'
EOF
chmod 600 "${ENV_FILE}"

cat <<BANNER
=================== OpenOMS (Home Assistant add-on) ===================
  dashboard : http://[HOST]:3000
  api       : http://[HOST]:8080  (Swagger at /swagger/)
  data dir  : /data  (postgres, redis, uploads)
  log_level : ${LOG_LEVEL}
=======================================================================
BANNER

exec "$@"
